name: Deploy Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Astro Site
        run: npm run build

      - name: Copy .htaccess
        run: |
          cp .htaccess dist/
          cp wordpress/.htaccess dist/blog/

      - name: Prepare WordPress Files
        run: |
          mkdir -p dist/blog
          cp -r wordpress/wp-content/themes/quicksummit dist/blog/wp-content/themes/
          cp -r wordpress/wp-content/plugins/quicksummit-* dist/blog/wp-content/plugins/

      - name: Deploy to Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: /home/admin/web/quicksummit.net/public_html/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            wp-config.php
            **/*.log
            **/debug.php
            **/info.php
            **/test*.php
