name: Deploy Website

on:
  push:
    branches:
      - deployment
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: |
          echo "Building Astro site..."
          npm run build
          echo "Build complete. Contents of dist directory:"
          ls -la dist/

      - name: Copy .htaccess
        run: cp .htaccess dist/

      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Deploy with lftp
        env:
          FTP_USER: ${{ secrets.REMOTE_USER }}
          FTP_PASS: ${{ secrets.REMOTE_PASSWORD }}
          FTP_HOST: ${{ secrets.REMOTE_HOST }}
        run: |
          lftp -c "
          set ftp:ssl-allow no;
          set ssl:verify-certificate no;
          open ftp://${FTP_HOST};
          user ${FTP_USER} '${FTP_PASS}';
          mirror -R -e -v ./dist/ /home/admin/web/quicksummit.net/public_html/;
          bye;
          "

      - name: Verify deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: 22
          script: |
            echo "Files in web directory:"
            ls -la /home/admin/web/quicksummit.net/public_html/
