name: Deploy Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Clean Build Directory
        run: rm -rf dist/

      - name: Build Astro Site
        run: npm run build

      # Create initial directory structure
      - name: Create Directory Structure
        run: |
          mkdir -p dist/blog/wp-content/themes
          mkdir -p dist/blog/wp-content/plugins

      # Create WordPress environment file
      - name: Create WordPress Environment File
        run: |
          cat > dist/blog/.env << EOL
          define('DB_NAME_ENV', '${{ secrets.WP_DB_NAME }}');
          define('DB_USER_ENV', '${{ secrets.WP_DB_USER }}');
          define('DB_PASSWORD_ENV', '${{ secrets.WP_DB_PASSWORD }}');
          define('DB_HOST_ENV', '${{ secrets.WP_DB_HOST }}');
          EOL

      # Debug step to check dist contents
      - name: List dist contents
        run: |
          echo "Contents of dist directory:"
          ls -la dist/

      # Ensure public assets are copied
      - name: Copy Public Assets
        run: |
          cp -r public/* dist/

      # Copy WordPress files
      - name: Copy WordPress Files
        run: |
          cp -r wordpress/* dist/blog/
          cp web.config dist/

      # First deployment step - ensure directory exists
      - name: Create Remote Directory
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          script: |
            mkdir -p /home/admin/web/quicksummit.net/public_html

      # Second deployment step - clean only non-WordPress directories
      - name: Clean Non-WordPress Directories
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          script: |
            cd /home/admin/web/quicksummit.net/public_html
            # Remove everything except the blog directory
            find . -maxdepth 1 ! -name 'blog' ! -name '.' -exec rm -rf {} +

      # Set proper WordPress permissions
      - name: Set WordPress Permissions
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          script: |
            # Set directory permissions
            find /home/admin/web/quicksummit.net/public_html/blog -type d -exec chmod 755 {} \;
            # Set file permissions
            find /home/admin/web/quicksummit.net/public_html/blog -type f -exec chmod 644 {} \;
            # Make wp-config.php and .env more secure
            chmod 600 /home/admin/web/quicksummit.net/public_html/blog/wp-config.php
            chmod 600 /home/admin/web/quicksummit.net/public_html/blog/.env
            # Ensure web server user owns WordPress files
            chown -R www-data:www-data /home/admin/web/quicksummit.net/public_html/blog

      # Final deployment step - upload new files
      - name: Deploy to Server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.FTP_USERNAME }}
          server: ${{ secrets.FTP_SERVER }}
          port: 22
          password: ${{ secrets.FTP_PASSWORD }}
          local_path: './dist/*'
          remote_path: '/home/admin/web/quicksummit.net/public_html'
          sftp_only: true
          delete_remote_files: false
