name: Deploy Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Clean Build Directory
        run: rm -rf dist/

      - name: Build Astro Site
        run: npm run build

      # Debug step to check dist contents
      - name: List dist contents
        run: |
          echo "Contents of dist directory:"
          ls -la dist/

      # Ensure public assets are copied
      - name: Copy Public Assets
        run: |
          cp -r public/* dist/

      # Copy WordPress files
      - name: Copy WordPress Files
        run: |
          mkdir -p dist/blog
          cp -r wordpress/* dist/blog/
          cp web.config dist/

      # First deployment step - ensure directory exists
      - name: Create Remote Directory
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          script: |
            mkdir -p /home/admin/web/quicksummit.net/public_html

      # Second deployment step - clean only non-WordPress directories
      - name: Clean Non-WordPress Directories
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          script: |
            cd /home/admin/web/quicksummit.net/public_html
            # Remove everything except the blog directory
            find . -maxdepth 1 ! -name 'blog' ! -name '.' -exec rm -rf {} +

      # Final deployment step - upload new files
      - name: Deploy to Server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.FTP_USERNAME }}
          server: ${{ secrets.FTP_SERVER }}
          port: 22
          password: ${{ secrets.FTP_PASSWORD }}
          local_path: './dist/*'
          remote_path: '/home/admin/web/quicksummit.net/public_html'
          sftp_only: true
          delete_remote_files: false
