name: Deploy Website

on:
  push:
    branches:
      - deployment
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: |
          echo "Building Astro site..."
          npm run build
          echo "Build complete. Contents of dist directory:"
          ls -la dist/

      - name: Copy .htaccess
        run: cp .htaccess dist/

      - name: Prepare server directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: 22
          script: |
            # Create temp directory with proper permissions
            rm -rf ~/deploy-temp
            mkdir -p ~/deploy-temp
            chmod 755 ~/deploy-temp

      - name: Deploy built files via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.REMOTE_USER }}
          server: ${{ secrets.REMOTE_HOST }}
          port: 22
          local_path: './dist/*'
          remote_path: '/home/linuxuser/deploy-temp/'
          sftp_only: true
          password: ${{ secrets.REMOTE_PASSWORD }}

      - name: Verify deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: 22
          script: |
            echo "Files ready in temporary directory:"
            ls -la ~/deploy-temp/
            
            echo "Creating deploy script..."
            cat > ~/deploy.sh << 'EOL'
            #!/bin/bash
            if [ -d "/home/linuxuser/deploy-temp" ] && [ "$(ls -A /home/linuxuser/deploy-temp)" ]; then
              echo "Found files to deploy at $(date)"
              sudo rm -rf /home/admin/web/quicksummit.net/public_html/*
              sudo cp -r /home/linuxuser/deploy-temp/* /home/admin/web/quicksummit.net/public_html/
              sudo chown -R admin:admin /home/admin/web/quicksummit.net/public_html/
              sudo find /home/admin/web/quicksummit.net/public_html/ -type d -exec chmod 755 {} \;
              sudo find /home/admin/web/quicksummit.net/public_html/ -type f -exec chmod 644 {} \;
              echo "Deployment complete at $(date)"
            fi
            EOL
            
            chmod +x ~/deploy.sh
            echo "Created deploy script. Set up a cron job to run this script periodically."
