name: Deploy Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Clean Build Directory
        run: rm -rf dist/

      - name: Build Astro Site
        run: npm run build

      - name: Prepare Directories
        run: |
          mkdir -p dist/blog/wp-content/themes
          mkdir -p dist/blog/wp-content/plugins

      - name: Copy .htaccess Files
        run: |
          cp .htaccess dist/
          cp wordpress/.htaccess dist/blog/

      - name: Copy WordPress Files
        run: |
          cp -r wordpress/wp-content/themes/quicksummit dist/blog/wp-content/themes/
          cp -r wordpress/wp-content/plugins/quicksummit-* dist/blog/wp-content/plugins/ || true

      - name: Deploy to Server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.FTP_USERNAME }}
          server: ${{ secrets.FTP_SERVER }}
          port: 22
          password: ${{ secrets.FTP_PASSWORD }}
          local_path: './dist/*'
          remote_path: '/home/admin/web/quicksummit.net/public_html'
          sftp_only: true
          delete_remote_files: true
