name: Deploy Website

on:
  push:
    branches:
      - deployment
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Copy .htaccess
        run: cp .htaccess dist/

      - name: Debug SSH Setup
        run: |
          echo "Starting deployment process..."
          echo "Checking secrets..."
          echo "REMOTE_HOST is set: ${{ secrets.REMOTE_HOST != '' }}"
          echo "REMOTE_USER is set: ${{ secrets.REMOTE_USER != '' }}"
          echo "REMOTE_PORT is set: ${{ secrets.REMOTE_PORT != '' }}"
          echo "SSH_PRIVATE_KEY is set: ${{ secrets.SSH_PRIVATE_KEY != '' }}"
          
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          
          echo "Writing SSH key..."
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          
          echo "Adding known hosts..."
          ssh-keyscan -p "${{ secrets.REMOTE_PORT }}" "${{ secrets.REMOTE_HOST }}" >> ~/.ssh/known_hosts 2>/dev/null
          chmod 644 ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: |
          echo "Testing SSH connection to ${{ secrets.REMOTE_HOST }}..."
          ssh -v -i ~/.ssh/deploy_key \
              -p "${{ secrets.REMOTE_PORT }}" \
              "${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}" \
              "echo Connected successfully as \$(whoami) in \$(pwd)"

      - name: Deploy with rsync
        if: success()
        run: |
          echo "Starting rsync deployment to ${{ secrets.REMOTE_HOST }}..."
          rsync -avz --delete \
            -e "ssh -i ~/.ssh/deploy_key -p ${{ secrets.REMOTE_PORT }}" \
            dist/ \
            "${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/${{ secrets.REMOTE_USER }}/web/quicksummit.net/public_html/"
