name: Deploy Website

on:
  push:
    branches:
      - deployment
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: |
          echo "Building Astro site..."
          npm run build
          echo "Build complete. Contents of dist directory:"
          ls -la dist/

      - name: Copy .htaccess
        run: cp .htaccess dist/

      - name: Prepare deploy directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: 22
          script: |
            # Clean up deploy-temp directory
            rm -rf ~/deploy-temp/*
            mkdir -p ~/deploy-temp

      - name: Deploy built files via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.REMOTE_USER }}
          server: ${{ secrets.REMOTE_HOST }}
          port: 22
          local_path: './dist/*'
          remote_path: '/home/linuxuser/deploy-temp/'
          sftp_only: true
          password: ${{ secrets.REMOTE_PASSWORD }}

      - name: Verify deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: 22
          script: |
            echo "Files uploaded to deploy-temp:"
            ls -la ~/deploy-temp/
            
            echo "Waiting for cron job to process files..."
            sleep 65
            
            echo "Files in web directory:"
            ls -la /home/admin/web/quicksummit.net/public_html/
