name: Deploy Website

on:
  push:
    branches:
      - deployment
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Copy .htaccess
        run: cp .htaccess dist/

      - name: Set up SSH connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: 22
          script: |
            mkdir -p /home/admin/deploy/site

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.REMOTE_USER }}
          server: ${{ secrets.REMOTE_HOST }}
          port: 22
          local_path: './dist/*'
          remote_path: '/home/admin/deploy/site/'
          sftp_only: true
          password: ${{ secrets.REMOTE_PASSWORD }}

      - name: Copy files and fix ownership
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: 22
          script: |
            # Clear the destination directory first
            sudo rm -rf /home/admin/web/quicksummit.net/public_html/*
            
            # Copy files
            sudo cp -r /home/admin/deploy/site/* /home/admin/web/quicksummit.net/public_html/
            
            # Fix ownership - this is crucial
            sudo chown -R admin:admin /home/admin/web/quicksummit.net/public_html/
            
            # Set directory permissions
            sudo find /home/admin/web/quicksummit.net/public_html/ -type d -exec chmod 755 {} \;
            
            # Set file permissions
            sudo find /home/admin/web/quicksummit.net/public_html/ -type f -exec chmod 644 {} \;
            
            # Verify the changes
            echo "Checking ownership and permissions:"
            ls -la /home/admin/web/quicksummit.net/public_html/
